name: macOS with Chrome Remote Desktop

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Homebrew
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    
    - name: Install Chrome Remote Desktop
      run: |
        brew install --cask google-chrome
        brew install --cask chrome-remote-desktop-host

    - name: Start Chrome Remote Desktop
      env:
        CHROME_REMOTE_DESKTOP_CODE: ${{ secrets.CHROME_REMOTE_DESKTOP_CODE }}
      run: |
        /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --remote-debugging-port=9222 &
        /Applications/Chrome\ Remote\ Desktop\ Host.app/Contents/MacOS/chrome-remote-desktop-host --start-host

    - name: Verify working directory
      run: pwd

    - name: List current directory contents
      run: ls -la

    - name: Setting the Environment Up
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        USER_PWD: ${{ secrets.USER_PWD }}
        AMI_PEM: ${{ secrets.AMI_PEM }}
        BACKUP_SRC: ${{ secrets.BACKUP_SRC }}
        AWS_EC2: ${{ secrets.AWS_EC2 }}
      run: |
        chmod +x setup.sh
        ./setup.sh "$USER_PWD" "$USER_PWD" "$NGROK_AUTH_TOKEN" "$BACKUP_SRC" "$AWS_EC2"

    - name: ngrok is now listening to SSH connections on...
      run: curl --silent http://127.0.0.1:4040/api/tunnels | jq '.tunnels[0].public_url'

    - name: Setup tmate Session
      uses: mxschmitt/action-tmate@v2
